name: CI Pipeline

on:
  workflow_call:

jobs:
  ci:
    name: Code Formatting & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-project

      - name: Check Code Formatting
        run: npx prettier --check "**/*.{ts,js,json,html,scss,md}"

      - name: Nx Affected Lint
        run: npx nx affected -t lint
